version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goexpert
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      mysql_net:
        ipv4_address: 192.168.157.51

networks:
  mysql_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.157.0/24